# Cloudflare Pages build configuration for DataMonkey3 Storybook
[build]
command = "yarn install --immutable && yarn build-storybook"
publish = "storybook-static"

[build.environment]
NODE_VERSION = "20"

# Only rebuild on changes to these paths
[build.watch]
include = [
  "src/stories/**",
  "src/lib/**", 
  ".storybook/**",
  "package.json",
  "yarn.lock",
  "package-lock.json"
]