name: Deploy Storybook to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'src/stories/**'
      - 'src/lib/**'
      - '.storybook/**'
      - 'package.json'
  pull_request:
    branches: [main]
    paths:
      - 'src/stories/**'
      - 'src/lib/**'
      - '.storybook/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: fasta-validation-storybook
          directory: storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
